<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name', 'is_directory','level','path'];
    protected $casts = [
        'is_directory' => 'boolean',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        // 监听category创建事件，用户初始化path和level字段
        static::creating(function (Category $category) {
            // 如果创建的是一个根目录
            if(is_null($category->parent_id)) {
                $category->level = 0;
                $category->path = '-';
            } else {
                $category->level = $category->parent->level + 1;
                $category->path = $category->parent->path.$category->parent_id.'-';
            }
        });
    }

    public function parent(){
        return $this->belongsTo(Category::class, 'parent_id');
    }

    public function products() {
        return $this->hasMany(Product::class);
    }

    public function getPathIdsAttribute() {
        return array_filter(explode('-',trim($this->path, '-')));
    }

    public function getAncestorsAttribute() {
        return Category::query()->whereIn('id',$this->path_ids)->orderBy('level')->get();
    }

    public function getFullNameAttribute() {
        return $this->ancestors->pluck('name')->push($this->name)->implode('-');
    }
}
